# Generated by Django 2.0.3 on 2018-04-16 02:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='pic', max_length=150)),
                ('pic', models.CharField(default='pic', max_length=250)),
                ('timeupload', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
